#!/bin/bash
which phonegap > /dev/null 2>&1
if [ "$?" -eq "0" ]; then
    phonegap plugin add cordova-plugin-customurlscheme --variable URL_SCHEME=xrpl
else
    cordova plugin add cordova-plugin-customurlscheme --variable URL_SCHEME=xrpl
fi

