#!/bin/bash
cp platforms/android/assets/www/cordova_plugins.js platforms/android/assets/www/cordova_plugins_.js
cat platforms/android/assets/www/cordova_plugins_.js | pcregrep -Mv '{\s+"id": "it.almaviva.openurlext.OpenUrlExt"[^\[\]}]*?}' | tr '\n' '%' | sed 's/},%\s*];/}%];/g' | tr '%' '\n' > platforms/android/assets/www/cordova_plugins.js
rm platforms/android/assets/www/cordova_plugins_.js
touch android_bc_ran
